spring:
  application:
    name: growth

  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_and_stop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/airbnb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Mysql1234}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
        generate_statistics: false
    show-sql: true
    open-in-view: false

# TODO: 시크릿 키 env 설정
jwt:
  secret: ${JWT_SECRET:PHNHLG1nm+wTX2Ktwi/0OsFwiBKS6vIek+uOtnAe1/k=}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000} # 1시간 (밀리초)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7일 (밀리초)

# Cookie 보안 설정
cookie:
  http-only: ${COOKIE_HTTP_ONLY:true} # JavaScript 접근 차단 (XSS 방지)
  secure: ${COOKIE_SECURE:false} # 개발환경: false(HTTP), 프로덕션: true(HTTPS)
  same-site: ${COOKIE_SAME_SITE:Lax} # CSRF 방지 (Strict, Lax, None)
