spring:
  application:
    name: growth

  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_and_stop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3307/airbnb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:1234}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
        generate_statistics: false
    show-sql: true
    open-in-view: false