spring:
  application:
    name: growth

  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_and_stop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/airbnb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:Mysql1234}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
        generate_statistics: false
    show-sql: true
    open-in-view: false

# TODO: 시크릿 키 env 설정
jwt:
  secret: ${JWT_SECRET:PHNHLG1nm+wTX2Ktwi/0OsFwiBKS6vIek+uOtnAe1/k=}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000} # 1시간 (밀리초)
